---
apiVersion: v1
kind: Service
metadata:
  name: helloWorld-boot-docker
  namespace: voltest
  labels:
    app: helloWorld-boot-docker

spec:
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 61005
      targetPort: http
  selector:
    app: helloWorld-boot-docker
